### ISSUE TITLE
ascii.element throws in environments where the DOM is not fully implemented

### ISSUE THREAD

**Issue by grommett** [sinonjs/formatio#29]
### This is not a bug report as much as it is to document.

In some Node environments the `DOM` is not fully implemented. In my case using [basicHTML](https://github.com/WebReflection/basicHTML). In this senario the `ascii.element` function assumes that the `element` being passed in as the argument fully implements [`NamedNodeMap`](https://dom.spec.whatwg.org/#interface-namednodemap) and calls the `item` method.

* library version : 3.1.0
* Environment   : Node
* Other libraries you are using: Sinon, Referee, referee-plugin-dom

**What did you expect to happen?**
That formatio would check that `item` was a method on the `attrs` object before calling it.

**What actually happens**
`attrs.items` is called without checking and an error is thrown

**How to reproduce**
- Clone https://github.com/sinonjs/referee-plugin-dom
- `npm install && npm install basichtml --save-dev`
- Edit `demo/index.test.js`
  Replace `require("jsdom-global")();` with `require('basichtml').init();`
- Execute `npm run demo`
- Observe that an error is thrown

<details>
    <summary>Stacktrace</summary>

```
TypeError: attrs.item is not a function
    at Function.ascii.element (/Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/formatio/lib/formatio.js:186:22)
    at ascii (/Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/formatio/lib/formatio.js:78:50)
    at Formatio.ascii (/Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/formatio/lib/formatio.js:227:16)
    at format (/Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/referee/lib/format.js:18:28)
    at /Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/referee/lib/interpolate-properties.js:21:23
    at Array.reduce (<anonymous>)
    at interpolateProperties (/Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/referee/lib/interpolate-properties.js:15:12)
    at Object.fail (/Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/referee/lib/define-assertion.js:32:27)
    at assertion (/Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/referee/lib/define-assertion.js:68:17)
    at Function.referee.(anonymous function).(anonymous function) [as tagName] (/Users/david/Documents/work/referee-plugin-dom/node_modules/@sinonjs/referee/lib/define-assertion.js:93:26)
    at Context.<anonymous> (/Users/david/Documents/work/referee-plugin-dom/demo/basic-html.test.js:37:32)
    at callFn (/Users/david/Documents/work/referee-plugin-dom/node_modules/mocha/lib/runnable.js:387:21)
    at Test.Runnable.run (/Users/david/Documents/work/referee-plugin-dom/node_modules/mocha/lib/runnable.js:379:7)
    at Runner.runTest (/Users/david/Documents/work/referee-plugin-dom/node_modules/mocha/lib/runner.js:525:10)
    at /Users/david/Documents/work/referee-plugin-dom/node_modules/mocha/lib/runner.js:643:12
    at next (/Users/david/Documents/work/referee-plugin-dom/node_modules/mocha/lib/runner.js:437:14)
    at /Users/david/Documents/work/referee-plugin-dom/node_modules/mocha/lib/runner.js:447:7
    at next (/Users/david/Documents/work/referee-plugin-dom/node_modules/mocha/lib/runner.js:362:14)
    at Immediate.<anonymous> (/Users/david/Documents/work/referee-plugin-dom/node_modules/mocha/lib/runner.js:415:5)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
</details>

**Comment by mantoni** [comment]
My first reaction to this is that we shouldn’t start working around broken libraries. We already have enough trouble with that broken browser.

**Comment by grommett** [comment]
@mantoni - Completely understand. 

I thought it was worth documenting since `formatio` is used with Referee and there's an amazing new plugin that will be testing `DOM` stuff. 😁

**Comment by mroderick** [comment]
This package has been deprecated in favour of using `util.inspet` in the Sinon projects
